expname : dlv3plus_res101

batchsize : 8
epochs : 120
classes : 
- stas

aug:
  resize_height: 640
  # width = height * 2

model :
  type : DeepLabV3Plus         
  # 'Unet'
  encoder_name : resnet101            
  # 'resnet50', 'resnet101', 'efficientnet-b4'
  encoder_weights : imagenet
  # 'noisy-students' 'ssl'
  activation : sigmoid

loss :
  type : DiceLoss

optim : 
  type : Adam
  lr : !!float 1e-4

sched :
  type : CosineAnnealingWR
  T_0 : 4
  T_mult : 2