expname : 'dlv3plus_res50'

batchsize : 8
epochs : 100
classes : ['stas']

aug:
  resize_width : 1280
  resize_height: 640

model :
  type : 'DeepLabV3Plus'                # 'Unet'
  encoder_name : 'resnet50'             # 'resnet50'
  encoder_weights : 'imagenet'          # 'noisy-students' 'ssl'
  activation : 'sigmoid' 

optim : 
  type : 'Adam'
  lr : !!float 1e-4

sched :
  type : 'CosineAnnealingWR'
  T_0 : 4
  T_mult : 2